### ISSUE TITLE
Unable To Run .find()

### ISSUE THREAD

**Issue by Skillz4Killz** [denodrivers/deno_mongo#116]
```ts
0|mod  | error: Uncaught Error: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers:...... }
0|mod  |       if (error) command.reject(new Error(error));
0|mod  | ^
0|mod  |     at Array.<anonymous> (<https://deno.land/x/mongo@v0.12.1/ts/util.ts>:52:1)
0|mod  |     at handleAsyncMsgFromRust (core.js:182:34)
```

![image](https://user-images.githubusercontent.com/23035000/95522251-99358580-0999-11eb-8fbe-676c22e7d362.png)
![image](https://user-images.githubusercontent.com/23035000/95522258-9dfa3980-0999-11eb-91b0-3d2679f94354.png)
![image](https://user-images.githubusercontent.com/23035000/95522279-ac485580-0999-11eb-80a9-16aa4c8bad1d.png)

```ts
deno --version
deno 1.4.4
v8 8.7.75
typescript 4.0.3
```

**Comment by Skillz4Killz** [comment]
Is this repo still being maintained?

**Comment by benluu** [comment]
I file the same issue: https://github.com/manyuanrong/deno_mongo/issues/110

It doesn't seem like there is any other alternative.  Unfortunately, this has been preventing us from developing anything with deno since connecting to mongodb replica is pretty much required for anything we do with production data.

**Comment by manyuanrong** [comment]
The project has just been refactored, you can verify again whether the problem still exists

**Comment by chansdad** [comment]
deno --version
deno 1.5.4 (bc79d55, release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.0.5

with version 0.13.0 - mongo calls work as long as the id is supplied exists in the mongo collection. if the id does not exist , then it crashes the server. findOne , UpdateById , DeleteById , just crash the running deno server.

So I moved to  version 0.20.0 and also tried with version 0.20.1
with this change none of the calls work. cannot even get the documents out usign find(). Started to compare examples. At first after looking at examples i thought may be it is to do with the ObjectId  as i was letting mongo create it by default , and not generating using uuid, but seems like the issue is more related to permissions .. seems like the connection is not authorized after all .

Here is a simple test i did . Note that for the dbUrl I tried appending the dbname at the end of the url and without the dbname at the end of the url . Commented code works , uncomented code with mongo@v0.20.0 or @v0.20.1 does not.
```

**testdb.ts - testing file contents**

const dbUrl = mongodb://testuser:testuserPa$$@mongohost:27017/testdb"
const mydb = "testdb";

// import { MongoClient } from "https://deno.land/x/mongo@v0.13.0/mod.ts";
// const client = new MongoClient();
// await client.connectWithUri(dbUrl);
// const db = client.database(mydb);
// const names = await db.listCollectionNames();
// console.log(" this is the names of collection " , names);


import { MongoClient } from "https://deno.land/x/mongo@v0.20.1/mod.ts";
const client = new MongoClient();
await client.connect(dbUrl);
const db = client.database(mydb);
const names = await db.listCollectionNames();
console.log(" this is the names of collection " , names);
```


here is the error i am seeing 
```
error: Uncaught (in promise) Error: MongoError: {"ok":0,"errmsg":"command listCollections requires authentication","code":13,"codeName":"Unauthorized"}
      throw new MongoError(maybeError);
            ^
    at WireProtocol.commandSingle (protocol.ts:34:13)
    at async CommandCursor.<anonymous> (database.ts:47:28)
    at async CommandCursor.execute (cursor.ts:34:21)
    at async CommandCursor.next (cursor.ts:48:7)
    at async CommandCursor.[Symbol.asyncIterator] (cursor.ts:67:13)
    at async Database.listCollectionNames (database.ts:74:22)
    at async testdb.ts:17:15
```

**Comment by manyuanrong** [comment]
v0.20.x does not support authorization yet

**Comment by dl90** [comment]
I was able get the results from find() by applying .toArray() on the FindCursor {}, which is returned by find()
```js
const cursor = await collection.find()
const results = await cursor.toArray()
```

**Comment by manyuanrong** [comment]
v0.21.0 is supported
