### ISSUE TITLE
Is it stable/production-ready?

### ISSUE THREAD

**Issue by erfanium** [denodrivers/deno_mongo#36]
I want to migrate my app from node to deno. Is `deno_mongo` safe for production use?
It's better to specify the status of this package somewhere.

**Comment by alirealasad** [comment]
its a great library but it's in early stages because deno itself is also in its infancy. in my opinion, if you want to create some side projects that will be fine but if you want to create or migrate any business logic app or production use. I won't recommend it right now because deno is unstable, API's might also change anytime. 

BTW I'm not a Collaborator of this library take my words with a grain of salt

**Comment by richidev58** [comment]
@erfanium you can do it but my advice is to wait until a port of mongoose to Deno is ready. Right now only CRUD operations can be made using this library.

**Comment by erfanium** [comment]
@richidev58 Mongoose also needs a driver, so there's no mongoose for Deno until a trusted and reliable driver build.

**Comment by KotadiyaHiral** [comment]
Is deno_mongo is safe for production now.?
